### ISSUE TITLE
ISO/CS comment: **-081 Remove all other bold type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#162]
MB/NC1 | Line number | Clause/Subclause | Paragraph/Figure/Table | Type of comment2 | Comments | Proposed change | Observations of the secretariat
-- | -- | -- | -- | -- | -- | -- | --
**-081 |   | General: bold type |   | Ed | Only the term should be in bold type.Remove all other bold type (including the term used in other parts of the definition). |   | Is this an accessibility issue?

Given a first sentence like this:
`data/modules/shape_data_quality_criteria/arm_descriptions.xml`:

```xml
<ext_description linkend="Shape_data_quality_criteria_arm.Partly_overlapping_edges">
        A <b>Partly_overlapping_edges</b> is a type of
        <express_ref linkend="shape_data_quality_criteria:arm:Shape_data_quality_criteria_arm.Topology_related_to_overlapping_geometry" />.
```

This first sentence is normally included in the concept as a (the first) NOTE. Instead of doing this:
<img width="963" alt="Screenshot 2023-05-04 at 1 16 20 PM" src="https://user-images.githubusercontent.com/11865/236188890-65b8268e-7e73-417e-a71c-c3e63d905b2f.png">

We want to remove the bolding:
<img width="968" alt="Screenshot 2023-05-04 at 1 16 33 PM" src="https://user-images.githubusercontent.com/11865/236189196-0408246c-df29-40f9-86c1-c481672921c3.png">

i.e. we need to remove the `<b>...</b>` of the entity name when extracting the first sentence into the NOTE.

**Comment by ronaldtse** [comment]
@TRThurman I think there is a need to differentiate EXPRESS entity names vs normal english content. Can we use monospace for these items?

**Comment by stuartgalt** [comment]
This issue is basically the sam as **-093, **-094.  I am hoping we can go with: "Noted: The use of bold text is fundamental to the understanding of the STEP standard and identifying the EXPRESS constructs."

In the WG12 call today people were pretty against removing the bold characters.  It would be nice to be able to informally talk with the editor to see how firm of a comment this one is.

**Comment by ronaldtse** [comment]
@stuartgalt in this case we need to discuss the comment with Claudia our EPM:
* https://www.iso.org/committee/54158.html

Ultimately we may have to talk to Brian Stanton who is the chief editor.

I'm pretty sure that ISO will come back and use these two points:
* ISO DIR 2 only allows bold to indicate "preferred terms" in clause 3

<img width="632" alt="Screenshot 2023-05-12 at 7 10 09 AM" src="https://github.com/metanorma/stepmod-utils/assets/11865/e37669eb-392d-4497-824e-6da9a44df4d8">

* ISO House Style

<img width="658" alt="Screenshot 2023-05-12 at 7 10 25 AM" src="https://github.com/metanorma/stepmod-utils/assets/11865/072eead0-855f-4f1c-b3da-321af124f67a">

> In the WG12 call today people were pretty against removing the bold characters.

To me the only reason why SMRL was able to get away from this is because ISO/CS does not have manpower to review the HTML output.

If Claudia and Brian doesn't agree, and WG 12 insists, then we may need to submit an "Exception request" to TMB, backed by an SC 4 Resolution and the reasoning. WG 12 can do the work if they wish...

**Comment by TRThurman** [comment]
We may indeed need to go to the TMB.Brian worked directly with SC4 for years so is well aware of our standards, and did review them.TomSent from my iPhoneOn May 11, 2023, at 6:13 PM, Ronald Tse ***@***.***> wrote:﻿
@stuartgalt in this case we need to discuss the comment with Claudia our EPM:

https://www.iso.org/committee/54158.html

Ultimately we may have to talk to Brian Stanton who is the chief editor.
I'm pretty sure that ISO will come back and use these two points:

ISO DIR 2 only allows bold to indicate "preferred terms" in clause 3



ISO House Style



In the WG12 call today people were pretty against removing the bold characters.

To me the only reason why SMRL was able to get away from this is because ISO/CS does not have manpower to review the HTML output.
If Claudia and Brian doesn't agree, and WG 12 insists, then we may need to submit an "Exception request" to TMB, backed by an SC 4 Resolution and the reasoning. WG 12 can do the work if they wish...

**Comment by ronaldtse** [comment]
@TRThurman maybe it's easiest if you or @stuartgalt (as the PL) can directly bring it up with Brian? It would be so much more effective if this is something he has previously agreed with. I'm really bad with anticipation... 🤣

**Comment by TRThurman** [comment]
I agree this needs to be worked with Brian directly.
Maybe a joint email from Keith, Stuart.
Tom

**Comment by ronaldtse** [comment]
Agree with @TRThurman  👍  @stuartgalt could you help with this? Thanks!

**Comment by TRThurman** [comment]
I think we can close this issue.
Here is a clause in the FDIS document accepted by ISO for publication.
5.421.104
(rendering in this browser failed.)
