### ISSUE TITLE
bigeqn unrecognised

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#226]
In 10303-42 4.5.30, we are getting the following in Asciidoctor output:

````
The clothoid is parametrised as follows:

<bigeqn>
                        <b> &#x3BB;</b>
                        <i>(u)</i> = <b>C</b> + A&#x221A;{&#x3C0;}(&#x222B;<sub>0</sub>
                        <sup>
                                <i>u</i>
                        </sup>cos(&#x3C0;(<i>t<sup>2</sup>/2))dt</i>
                        <b>x</b> + &#x222B;<sub>0</sub>
                        <sup>
                                <i>u</i>
                        </sup>sin(&#x3C0;(<i>t<sup>2</sup>/2))dt</i>
                        <b>y</b>
                </bigeqn>

The parametrisation range is -∞ \< _u_ \< ∞
````

That means that bigeqn is not being recognised as markup; presumably we just treat it like any other equation...

**Comment by HassanAkbar** [comment]
@opoudjis @ronaldtse I have a question related to this task. What is `bigeqn`? How should I parse it? Is it same as `eqn` or are there some differences?

**Comment by HassanAkbar** [comment]
> I have a question related to this task. What is bigeqn? How should I parse it? Is it same as eqn or are there some differences?

@TRThurman Do you have any idea about it?

**Comment by TRThurman** [comment]
@HassanAkbar, it depends on whether the source is a resource or a module.
If it is a resource there is no difference.
If it is a module the only difference is that bigeqn does not have an id, which is stupid which means it can't be referenced intelligently.
Can you add a comment that the source type is bigeqn and otherwise treat it as eqn?

stepmod/dtd/text.ent (the module dtd)
<!ELEMENT eqn (%text-elts;)*>
<!ATTLIST eqn
         number     CDATA                              #IMPLIED
         id     CDATA                                  #IMPLIED>
         
<!ELEMENT bigeqn (%text-elts;)*>
<!ATTLIST bigeqn
         number     CDATA                              #IMPLIED  >
