### ISSUE TITLE
Move all EXPRESS-G diagrams (`[.svgmap]`) to Annex D and use anchors to reference them from annotated EXPRESS files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#66]
From https://github.com/metanorma/annotated-express/issues/35

Here's the sample commit that works:
https://github.com/metanorma/annotated-express/commit/db253f25488a162f4a2267f9312c62ebaeedf70d

**Comment by opoudjis** [comment]
This has never happened, and it has led to the raising of the issue https://github.com/metanorma/iso-10303/issues/233

SVGs in ISO-10303 are hyperlinked to placeholder destinations, given as numerals; e.g. `<a xlink:href="9">`. These need Metanorma `svgmap` wrappers, in order to map the SVG link destinations to cross-references understood by Metanorma. In the introduction section SVGs, this has been done correctly (although this had stopped working, and was only debugged in that ticket):

````
[.svgmap] 
====

image::schema_diagexpg1.svg[]

* <<express:product_property_representation_schema>>; 1
* <<express:support_resource_schema>>; 2
* <<express:geometric_model_schema>>; 3
* <<express:scan_data_3d_shape_model_schema>>; 4
* <<express:basic_attribute_schema>>; 5 
* <<express:measure_schema>>; 6
* <<express:representation_schema>>; 7
* <<express:topology_schema>>; 8
* <<express:geometry_schema>>; 9
====
````

The Lutaml templates for the SVGs in Annex D do not currently have any SVG Map wrappers, and as a result their hyperlinks are unresolved. This is what they currently look like:

````
{% if first_diagram %}
[[expg.{{ previous_name }}{%- if namespace -%} {{ namespace |  | prepend: '_' }} {%- endif -%}]]&#x200c;
{% assign first_diagram = false %}
{% endif %}

[[fig_expg_{{ figure_id }}{{ namespace }}]]
.{{ caption }}
image::{{ diagram.path }}[]

{% endfor %}
````

However the SVG links are resolved using svgmap in the introduction, the same needs to happen in Annex D, and that information needs to be made available in the Lutaml template for Annex D (which suggests to me that a standalone piece of Asciidoc is not the right solution). @Intelligent2013 you presumably need to work with @manuelfuenmayor on this.
